name: Security Scan
on:
  pull_request:
    types: [opened, reopened]
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Scan current project
      uses: anchore/scan-action@v3
      with:
        path: "."
